apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 

kind: Deployment 

metadata: 

  name: aspdotnet

spec: 

  selector: 

    matchLabels: 

      app:  aspdotnet 

  replicas: 5 # tells deployment to run 2 pods matching the template 

  template:

    metadata: 

      labels: 

        app:  aspdotnet 

    spec: 

      containers: 

      - name:  aspdotnet 

        image: gsrini23/azurepoctask:$(Build.BuildId)#

        ports: 

        - containerPort: 80 

--- 

# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  

kind: Service 

apiVersion: v1 

metadata: 

  name:  aspdotnetservice

spec: 

  selector: 

    app: aspdotnet

  ports: 

  - protocol: TCP 

    port: 80 

    targetPort: 80 

  type: LoadBalancer
